// @vitest-environment node
/**
 * The Generated Image save path: a cover-crop variant of the recipe-image
 * save. Generated bytes are stored at exactly 1280×720 whatever the provider
 * drew; uploads keep today's behaviour, fitting inside that box without
 * cropping. Runs against real sharp and a temp uploads dir, beside the
 * dish-colour media test.
 */
import { mkdtempSync } from "node:fs";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import sharp from "sharp";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const uploadsDir = mkdtempSync(path.join(os.tmpdir(), "generated-image-test-"));

vi.mock("@norish/config/env-config-server", () => ({
  SERVER_CONFIG: {
    UPLOADS_DIR: uploadsDir,
    MAX_IMAGE_FILE_SIZE: 5 * 1024 * 1024,
    // The mocked repository module sits in a graph whose crypto setup reads
    // a key at load time; any base64 value satisfies it.
    MASTER_KEY: "QmFzZTY0RW5jb2RlZE1hc3RlcktleU1pbjMyQ2hhcnM=",
  },
}));

const repository = vi.hoisted(() => ({
  replaceRecipePrimaryImageWithGenerated: vi.fn(),
}));

vi.mock("@norish/db/repositories/recipe-enrichment", () => repository);

vi.mock("@norish/shared-server/logger", () => {
  const logger = { debug: vi.fn(), info: vi.fn(), warn: vi.fn(), error: vi.fn() };

  return { serverLogger: logger, mediaLogger: logger, createLogger: () => logger };
});

const { saveGeneratedImageBytes, saveImageBytes } =
  await import("@norish/shared-server/media/storage");
const { storeGeneratedRecipeImage } = await import("@norish/shared-server/media/generated-image");

const RECIPE_ID = "0c7fcd0e-4f1a-4f5f-9a5e-92b1a54d21aa";

function jpeg(width: number, height: number, color = { r: 180, g: 90, b: 40 }): Promise<Buffer> {
  return sharp({ create: { width, height, channels: 3, background: color } })
    .jpeg()
    .toBuffer();
}

async function storedDimensions(url: string): Promise<{ width?: number; height?: number }> {
  const filePath = path.join(uploadsDir, url.replace(/^\//, ""));
  const metadata = await sharp(await fs.readFile(filePath)).metadata();

  return { width: metadata.width, height: metadata.height };
}

async function fileExists(url: string): Promise<boolean> {
  return fs
    .access(path.join(uploadsDir, url.replace(/^\//, "")))
    .then(() => true)
    .catch(() => false);
}

beforeEach(() => {
  vi.clearAllMocks();
});

afterEach(async () => {
  await fs.rm(path.join(uploadsDir, "recipes"), { recursive: true, force: true });
});

describe("saveGeneratedImageBytes", () => {
  it("stores a landscape source at exactly 1280×720", async () => {
    const url = await saveGeneratedImageBytes(await jpeg(1600, 900), RECIPE_ID);

    expect(url).toMatch(new RegExp(`^/recipes/${RECIPE_ID}/[a-f0-9-]+\\.jpg$`));
    expect(await storedDimensions(url)).toEqual({ width: 1280, height: 720 });
  });

  it("stores a square source at exactly 1280×720", async () => {
    const url = await saveGeneratedImageBytes(await jpeg(1024, 1024), RECIPE_ID);

    expect(await storedDimensions(url)).toEqual({ width: 1280, height: 720 });
  });

  it("still rejects what the upload path rejects", async () => {
    const garbage = Buffer.from("not an image at all, whatever the extension claims".repeat(10));

    await expect(saveGeneratedImageBytes(garbage, RECIPE_ID)).rejects.toThrow(/not a valid image/i);

    const tooLarge = Buffer.concat([await jpeg(64, 64), Buffer.alloc(6 * 1024 * 1024)]);

    await expect(saveGeneratedImageBytes(tooLarge, RECIPE_ID)).rejects.toThrow(/too large/i);
  });

  it("leaves the upload path uncropped: uploads still fit inside 1280×720", async () => {
    const url = await saveImageBytes(await jpeg(1600, 1200), RECIPE_ID);

    // 4:3 fits inside as 960×720; a crop would have produced 1280×720.
    expect(await storedDimensions(url)).toEqual({ width: 960, height: 720 });
  });
});

describe("storeGeneratedRecipeImage", () => {
  it("saves, replaces the primary row, and removes the displaced file", async () => {
    const displacedUrl = `/recipes/${RECIPE_ID}/displaced.jpg`;

    await fs.mkdir(path.join(uploadsDir, "recipes", RECIPE_ID), { recursive: true });
    await fs.writeFile(
      path.join(uploadsDir, "recipes", RECIPE_ID, "displaced.jpg"),
      await jpeg(64, 64)
    );
    repository.replaceRecipePrimaryImageWithGenerated.mockImplementation(
      async (_recipeId: string, imageUrl: string) => ({
        imageUrl,
        replacedImageUrls: [displacedUrl],
      })
    );

    const url = await storeGeneratedRecipeImage(RECIPE_ID, await jpeg(1600, 900));

    expect(repository.replaceRecipePrimaryImageWithGenerated).toHaveBeenCalledWith(RECIPE_ID, url);
    expect(await fileExists(url)).toBe(true);
    expect(await fileExists(displacedUrl)).toBe(false);
  });

  it("never deletes the file it just wrote, even when the replaced row held the same URL", async () => {
    // Content-hashed storage: a re-run over identical bytes lands on the
    // same path the previous Generated Image already occupies.
    repository.replaceRecipePrimaryImageWithGenerated.mockImplementation(
      async (_recipeId: string, imageUrl: string) => ({
        imageUrl,
        replacedImageUrls: [imageUrl],
      })
    );

    const url = await storeGeneratedRecipeImage(RECIPE_ID, await jpeg(1600, 900));

    expect(await fileExists(url)).toBe(true);
  });

  it("cleans up the saved file and fails when the recipe is gone", async () => {
    repository.replaceRecipePrimaryImageWithGenerated.mockResolvedValue(null);

    await expect(storeGeneratedRecipeImage(RECIPE_ID, await jpeg(1600, 900))).rejects.toThrow(
      /recipe/i
    );

    const recipeDir = path.join(uploadsDir, "recipes", RECIPE_ID);
    const leftover = await fs.readdir(recipeDir).catch(() => []);

    expect(leftover).toEqual([]);
  });
});
